### ISSUE TITLE
无法自动识别手机设备在线

### ISSUE THREAD

**Issue by XZ1314XZ** [qianqianjun/QiLinFastTransfer#1]
希望可以像feem那样强大，手机或者电脑端一打开就自动秒识别，自动获取到同在局域网下的设备

**Comment by XZ1314XZ** [comment]
> 希望可以像feem那样强大，手机或者电脑端一打开就自动秒识别，自动获取到同在局域网下的设备

期待你们的移动端产品，还有希望也是像feem那样实现p2p传输，不用放文件到对应的文件夹，直接在分享文件用该软件方式即可

**Comment by qianqianjun** [comment]
收到，有时间一定会完成移动端的开发，谢谢关注！
